#გამოიყენეთ print ფუნქცია და დაბეჭდეთ თქვენთვის სასურველი მნიშვნელობები 20-ჯერ.
print("hello world!")
print("მე მიყვარს python-ი")
print("chad")
print("მე ვარ დემეტრე")
print(2025)
print("Python არის ერთ-ერთი ყველაზე პოპულარული პროგრამირების ენა")
print("პროგრამირება გვასწავლის ლოგიკურ აზროვნებას")
print("პროგრამირება არის მაგარი")
print("GROUP 84 IS THE BEST!")
print(2)
print
print("GOA is the best programming academy")
print("i go to wrestling")
print("i like computers")
print("i like gaming but not too much")
print("i live in tbilisi")
print("i love georgia")
print("MMA is the best sport")
print("მე მიყვარს მწვადი")